# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - cyclomatic_complexity
  - identifier_name
  - trailing_whitespace
  - line_length
  - multiple_closures_with_trailing_closure
  - unused_enumerated
  - large_tuple
  - function_body_length
  - void_function_in_ternary
  - return_arrow_whitespace
  - empty_enum_arguments
  - type_body_length
  - blanket_disable_command
  - syntactic_sugar
  - operator_whitespace
  - unneeded_synthesized_initializer
  - switch_case_alignment
  - unneeded_override

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count # find all the available rules by running: `swiftlint rules`

included: 
  - Sources
excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - Carthage
  - Pods
  - Sources/ExcludedFolder
  - Sources/ExcludedFile.swift
  - Sources/*/ExcludedFile.swift # exclude files with a wildcard
  # configurable rules can be customized from this configuration file
# binary rules can set their severity level

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# they can set both implicitly with an array
# or they can set both explicitly
file_length:
  warning: 600
  error: 1300
function_parameter_count:
  warning: 10
  error: 11
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 60
    error: 70
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  max_length:
    warning: 80
    error: 100
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
# custom rules
custom_rules:
   space_between_functions:
     regex: '\}[^\n]*\n[^\n]*func'
     severity: error
     message: "functions should start with newline"
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)